### ISSUE TITLE
chat width view

### ISSUE THREAD

**Issue by MehdiMeidanshahi** [alikhalilifar/persian-twitch-client#2]
when a long text coming to the chat, the back of the chat goes out of the view
![image](https://github.com/alikhalilifar/persian-twitch-client/assets/22818495/ee637921-cf80-4a92-82aa-2c08960f85b4)

**Comment by alikhalilifar** [comment]
You could use ‘CTRL+R’ temporarily to reset the layout until I release a fix for it

**Comment by alikhalilifar** [comment]
This issue has been resolved and will be available in the next release.
